@base_url=http://localhost:8081

POST {{base_url}}/resources
Content-Type: application/json

{
    "userName"  : "JonDum88",
    "phone"     : "0856243152",
    "firstName" : "Jon",
    "lastname"  : "Doo"
}